# Change these first
owner: starkpay # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: Stark Website
    url: https://starkpayments.com
    expectedStatusCodes:
      - 200
  - name: Stark Dashboard
    url: https://dashboard.starkpayments.net
    expectedStatusCodes:
      - 200
  - name: Stark Payment Page
    url: https://pay.starkpayments.net
    expectedStatusCodes:
      - 200
  - name: Socket
    url: https://pay.starkpayments.net:3001
    expectedStatusCodes:
      - 200
  - name: Partner API
    url: https://k7reqv29ca.execute-api.us-east-1.amazonaws.com/prod/version
    expectedStatusCodes:
      - 200

assignees: # Users to assign downtime issues (optional)
  - starkpay
    
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/starkpay/status/master/assets/logo.png
  introTitle: "System status"
  introMessage: 
  css: "
    .logo div { display: none; }
    :root {
      --body-background-color: #f6f7f9;
      --body-text-color: #606b76;
      --card-background-color: #fff;
      --nav-background-color: #fff;
      --nav-border-bottom-color: #fff;
    }
  "
  name: Stark Payments - System & API Status
  navbar:
    - title: Home
      href: https://starkpayments.com
    - title: Status
      href: /
      
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/30 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
